Javadoc error fix for new ExecutionEnvironmentDescription constructor
See https://download.eclipse.org/eclipse/downloads/drops4/I20230925-1800/compilelogs/jdt.doc.isv.javadoc.txt

../../../eclipse.jdt.debug/org.eclipse.jdt.launching/launching/org/eclipse/jdt/launching/environments/ExecutionEnvironmentDescription.java:206:
error: exception not thrown: org.eclipse.core.runtime.CoreException
	 * @throws CoreException if unable to read or parse the file
	           ^

Regression from cc2c11c5c55636a71ab20d1d0805dbd7c5baece5